import { get, post, put, del } from './index.js';
export const getEmployees = (params) => get('/employees', params);
export const createEmployee = (data) => post('/employees', data);
export const updateEmployee = (id, data) => put(`/employees/${id}`, data);
export const deleteEmployee = (id) => del(`/employees/${id}`);
export const getPositions = () => get('/positions');
export const createPosition = (data) => post('/positions', data);
export const getDepartments = () => get('/departments');
export const getSchedules = (params) => get('/schedules', params);
export const createSchedule = (data) => post('/schedules', data);
export const updateSchedule = (id, data) => put(`/schedules/${id}`, data);
export const deleteSchedule = (id) => del(`/schedules/${id}`);
export const getAttendances = (params) => get('/attendances', params);
export const createAttendance = (data) => post('/attendances', data);
export const updateAttendance = (id, data) => put(`/attendances/${id}`, data);
export const deleteAttendance = (id) => del(`/attendances/${id}`);
export const getPayrolls = (params) => get('/payrolls', params);
export const createPayroll = (data) => post('/payrolls', data);
export const updatePayroll = (id, data) => put(`/payrolls/${id}`, data);
export const deletePayroll = (id) => del(`/payrolls/${id}`);
export const approvePayroll = (id) => put(`/payrolls/${id}/approve`);
