import { get, post, put, del } from './index.js';
export const getCashRecords = (params) => get('/cash-records', params);
export const getAccounts = () => get('/accounts');
export const createAccount = (data) => post('/accounts', data);
export const updateAccount = (id, data) => put(`/accounts/${id}`, data);
export const getJournalEntries = (params) => get('/journal-entries', params);
export const createJournalEntry = (data) => post('/journal-entries', data);
export const updateJournalEntry = (id, data) => put(`/journal-entries/${id}`, data);
export const deleteJournalEntry = (id) => del(`/journal-entries/${id}`);
export const postJournalEntry = (id) => put(`/journal-entries/${id}/post`);
export const getBudgets = (params) => get('/budgets', params);
export const createBudget = (data) => post('/budgets', data);
export const updateBudget = (id, data) => put(`/budgets/${id}`, data);
export const deleteBudget = (id) => del(`/budgets/${id}`);
export const approveBudget = (id) => put(`/budgets/${id}/approve`);
export const getTaxDeclarations = (params) => get('/tax-declarations', params);
export const createTaxDeclaration = (data) => post('/tax-declarations', data);
export const updateTaxDeclaration = (id, data) => put(`/tax-declarations/${id}`, data);
export const deleteTaxDeclaration = (id) => del(`/tax-declarations/${id}`);
export const createCashRecord = (data) => post('/cash-records', data);
