import { get, post, put, del } from './index.js';
export const getUsers = (params) => get('/users', params);
export const createUser = (data) => post('/users', data);
export const updateUser = (id, data) => put(`/users/${id}`, data);
export const toggleUserLock = (id) => put(`/users/${id}/lock`);
export const getRoles = () => get('/roles');
export const createRole = (data) => post('/roles', data);
export const updateRole = (id, data) => put(`/roles/${id}`, data);
export const deleteRole = (id) => del(`/roles/${id}`);
export const getPermissions = () => get('/permissions');
export const createPermission = (data) => post('/permissions', data);
export const updatePermission = (id, data) => put(`/permissions/${id}`, data);
export const deletePermission = (id) => del(`/permissions/${id}`);
export const getLogs = (params) => get('/logs', params);
export const getSystemConfigs = () => get('/system-configs');
export const createSystemConfig = (data) => post('/system-configs', data);
export const updateSystemConfig = (id, data) => put(`/system-configs/${id}`, data);
export const getBackupRecords = () => get('/backup-records');
export const createBackupRecord = (data) => post('/backup-records', data);
export const getOperationLogs = (params) => get('/operation-logs', params);
